### PR TITLE
Use HSE_BYPASS instead of HSI

### PR DESCRIPTION
**Pull request by fpistm**
This PR allows to configure the system core clock to use HSE_BYPASS instead of the HSI.

The `SYSCLK = 100000000` Hz for STM32F411xE
and `SYSCLK = 84000000 Hz` for STM32F401xE

### CODE REVIEW

**Comment by dsferruzza** [comment]
@fpistm Maybe this should be put in its own file so that we can easily include it in both three programs, right?

I'm talking about about these 3 "entry points" that can be "enabled/disabled" from `includes/config.h`:
- `srcs/respirator.cpp`
- `srcs/qualification.cpp`
- `srcs/integration_test.cpp`

**Comment by fpistm** [comment]
@dsferruzza 
yes of course

**Comment by dsferruzza** [comment]
@fpistm My last commit seems to compile; what do you think?

**Comment by fpistm** [comment]
I don't think you need the .h

**Comment by dsferruzza** [comment]
If not my linter say I can include a .cpp... Or maybe I don't need any include?

**Comment by fpistm** [comment]
You don't need any include, this is done by the core which declare it

**Comment by dsferruzza** [comment]
@fpistm So the current code should be alright?

@pi-r-p Could you test it when you have a bit of time, please?

**Comment by fpistm** [comment]
@dsferruzza yes all is right😉

**Pull request merged**
