### PR TITLE
Test Chip::new_event() with any sequence of TelemetryMessage

### PR DESCRIPTION
**Pull request by ronanM**
The idea is to be sure that `Chip::new_event()` don't crash with any sequence of `TelemetryMessage`.

This is a WIP, and I need some help for the reuse, in `control`, of the `proptest strategy` functions defined in `telemetry` tests (only `telemetry_message_strategy()` for the moment).

 As a Rust beginner I don't know how to configure `Cargo` to do that.

### CODE REVIEW

**Comment by BlackYoup** [comment]
Hello @ronanM ,

I'm not sure to understand the need of this. To me, once the data has been parsed it should be safe to be used. Testing the parser would be the best thing to do because if the input is invalid, it shouldn't be parsed into a TelemetryMessage and we should then discard it.

Or did I misunderstand this and proptest?

**Comment by ronanM** [comment]
@BlackYoup We must me sure that sequence of messages in any order and with any value on the domain (0..255 for u8, etc.) don't crash the system.

**Comment by BlackYoup** [comment]
The system will crash if it receives invalid input, it's not designed to not crash because the input has already been parsed by the parser. What comes out of the parser (the `TelemetryMessage` struct) has to be trusted but the parser's logic can't be trusted and should be tested.

**Comment by ronanM** [comment]
What about messages disorder test ?

(from my point of view, there is a difference between parsing and domain validation)

**Comment by ronanM** [comment]
With the addition of an ugly copy/paste to workaround the `Cargo` config, the test may found a problem and  panicked with a `DateTime + Duration overflowed`.

**Comment by BlackYoup** [comment]
> What about messages disorder test ?

It could make sense but for now, if we receive a message older than the previous one, we just reset the whole state, we don't try to be smarter. Other than that, the protocol doesn't define an order for the messages so the control UI updates accordingly. There might be logic errors but I think those might be better found with unit testing instead of using proptest.

> With the addition of an ugly copy/paste to workaround the Cargo config, the test may found a problem and panicked with a DateTime + Duration overflowed.

Indeed. I guess that's because the systick goes very big at some point, we overflow. We reach the i64 limit, that means the makair has been running for.. ~292 450 years. I hope we will have better medical equipment by then :D

To me proptest is aimed at testing untrusted input which would be perfect to test the telemetry lib since it's exactly what it receives. But the control UI can't receive output outside of the telemetry lib so there is no point of testing random input. Unit tests are on the contrary something we should have more.

**Comment by ronanM** [comment]
> The control UI can't receive output outside of the telemetry lib so there is no point of testing random input.

Does the protocol already include strong error detection and correction ?

**Comment by BlackYoup** [comment]
> Does the protocol already include strong error detection and correction ?

If by error you mean a malformed message, it should be dropped if the message is not successfully parsed. But if you pass any valid data, it will be parsed. As for correction, it doesn't because that's not the goal of this protocol.

**Comment by ronanM** [comment]
I've added `proptest` _"don't crash"_ GUI  test.

So for the moment, I've add somewhere in the GUI code this line:
```
assert!(v.1 <= 500, format!("This assert! is here only to show the effectiveness of the GUI tests ({} > 500)", v.1));
```

To run the test:
```
cargo test -- --nocapture
```

The test ended with minimal `Vec<TelemetryMessage>` (including `pressure: 501`):
```
[DataSnapshot(DataSnapshot { version: "", device_id: "0-0-0", systick: 1588427176487, centile: 0, pressure: 501, phase: Inhalation, subphase: Inspiration, blower_valve_position: 0, patient_valve_position: 0, blower_rpm: 0, battery_level: 0 })]
```

**Comment by dsferruzza** [comment]
I don't know the status of this PR but we split the repositories and now the control UI codebase is located here: https://github.com/makers-for-life/makair-control-ui

Should this be migrated?

**Comment by ronanM** [comment]
@dsferruzza Yes, this PR is a WIP proptest for Control GUI.

**Comment by dsferruzza** [comment]
> @dsferruzza Yes, this PR is a WIP proptest for Control GUI.

Cool! Could you (whenever you have time and are ready) re-open this PR in the new repo? Nothing more will happen here and soon I will be removing the software for this repo.

This might not go well because you did some merges in there (?) but sometimes it can be as easy as replaying [the patch](https://github.com/makers-for-life/makair/pull/214.patch) on a fork of the other repo after you changed the paths of the files.

**Pull request closed without merging**
